use_frameworks!

platform :ios, '9.0'

target 'TKWidgetModule_Example' do
  pod 'TKWidgetModule', :path => '../'
  pod 'LookinServer'
  target 'TKWidgetModule_Tests' do
    inherit! :search_paths

    
  end
end
